// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.1
// source: proto/testservice/testservice.proto

package testservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetFoosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetFoosRequest) Reset() {
	*x = GetFoosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_testservice_testservice_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFoosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoosRequest) ProtoMessage() {}

func (x *GetFoosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_testservice_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoosRequest.ProtoReflect.Descriptor instead.
func (*GetFoosRequest) Descriptor() ([]byte, []int) {
	return file_proto_testservice_testservice_proto_rawDescGZIP(), []int{0}
}

type GetFoosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foos []*Foo `protobuf:"bytes,1,rep,name=foos,proto3" json:"foos,omitempty"`
}

func (x *GetFoosResponse) Reset() {
	*x = GetFoosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_testservice_testservice_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFoosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoosResponse) ProtoMessage() {}

func (x *GetFoosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_testservice_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoosResponse.ProtoReflect.Descriptor instead.
func (*GetFoosResponse) Descriptor() ([]byte, []int) {
	return file_proto_testservice_testservice_proto_rawDescGZIP(), []int{1}
}

func (x *GetFoosResponse) GetFoos() []*Foo {
	if x != nil {
		return x.Foos
	}
	return nil
}

type Foo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Details []string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *Foo) Reset() {
	*x = Foo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_testservice_testservice_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foo) ProtoMessage() {}

func (x *Foo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_testservice_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foo.ProtoReflect.Descriptor instead.
func (*Foo) Descriptor() ([]byte, []int) {
	return file_proto_testservice_testservice_proto_rawDescGZIP(), []int{2}
}

func (x *Foo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foo) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

type GetFoobarsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FooId string `protobuf:"bytes,1,opt,name=foo_id,json=fooId,proto3" json:"foo_id,omitempty"`
}

func (x *GetFoobarsRequest) Reset() {
	*x = GetFoobarsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_testservice_testservice_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFoobarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoobarsRequest) ProtoMessage() {}

func (x *GetFoobarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_testservice_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoobarsRequest.ProtoReflect.Descriptor instead.
func (*GetFoobarsRequest) Descriptor() ([]byte, []int) {
	return file_proto_testservice_testservice_proto_rawDescGZIP(), []int{3}
}

func (x *GetFoobarsRequest) GetFooId() string {
	if x != nil {
		return x.FooId
	}
	return ""
}

type GetFoobarsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foobars []*Foobar `protobuf:"bytes,1,rep,name=foobars,proto3" json:"foobars,omitempty"`
}

func (x *GetFoobarsResponse) Reset() {
	*x = GetFoobarsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_testservice_testservice_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFoobarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFoobarsResponse) ProtoMessage() {}

func (x *GetFoobarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_testservice_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFoobarsResponse.ProtoReflect.Descriptor instead.
func (*GetFoobarsResponse) Descriptor() ([]byte, []int) {
	return file_proto_testservice_testservice_proto_rawDescGZIP(), []int{4}
}

func (x *GetFoobarsResponse) GetFoobars() []*Foobar {
	if x != nil {
		return x.Foobars
	}
	return nil
}

type Foobar struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Details []string `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
}

func (x *Foobar) Reset() {
	*x = Foobar{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_testservice_testservice_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Foobar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Foobar) ProtoMessage() {}

func (x *Foobar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_testservice_testservice_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Foobar.ProtoReflect.Descriptor instead.
func (*Foobar) Descriptor() ([]byte, []int) {
	return file_proto_testservice_testservice_proto_rawDescGZIP(), []int{5}
}

func (x *Foobar) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Foobar) GetDetails() []string {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_proto_testservice_testservice_proto protoreflect.FileDescriptor

var file_proto_testservice_testservice_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x73, 0x22, 0x2f, 0x0a,
	0x03, 0x46, 0x6f, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x2a,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6f, 0x6f, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x12, 0x47, 0x65,
	0x74, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x07, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x52, 0x07, 0x66, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73, 0x22,
	0x32, 0x0a, 0x06, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x32, 0xa2, 0x01, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x73, 0x12, 0x1b,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x74, 0x65,
	0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x62, 0x61, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x65, 0x39, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2d,
	0x6a, 0x73, 0x2d, 0x67, 0x6f, 0x2d, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74,
	0x65, 0x73, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_testservice_testservice_proto_rawDescOnce sync.Once
	file_proto_testservice_testservice_proto_rawDescData = file_proto_testservice_testservice_proto_rawDesc
)

func file_proto_testservice_testservice_proto_rawDescGZIP() []byte {
	file_proto_testservice_testservice_proto_rawDescOnce.Do(func() {
		file_proto_testservice_testservice_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_testservice_testservice_proto_rawDescData)
	})
	return file_proto_testservice_testservice_proto_rawDescData
}

var file_proto_testservice_testservice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_testservice_testservice_proto_goTypes = []interface{}{
	(*GetFoosRequest)(nil),     // 0: testservice.GetFoosRequest
	(*GetFoosResponse)(nil),    // 1: testservice.GetFoosResponse
	(*Foo)(nil),                // 2: testservice.Foo
	(*GetFoobarsRequest)(nil),  // 3: testservice.GetFoobarsRequest
	(*GetFoobarsResponse)(nil), // 4: testservice.GetFoobarsResponse
	(*Foobar)(nil),             // 5: testservice.Foobar
}
var file_proto_testservice_testservice_proto_depIdxs = []int32{
	2, // 0: testservice.GetFoosResponse.foos:type_name -> testservice.Foo
	5, // 1: testservice.GetFoobarsResponse.foobars:type_name -> testservice.Foobar
	0, // 2: testservice.TestService.GetFoos:input_type -> testservice.GetFoosRequest
	3, // 3: testservice.TestService.GetFoobars:input_type -> testservice.GetFoobarsRequest
	1, // 4: testservice.TestService.GetFoos:output_type -> testservice.GetFoosResponse
	4, // 5: testservice.TestService.GetFoobars:output_type -> testservice.GetFoobarsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_testservice_testservice_proto_init() }
func file_proto_testservice_testservice_proto_init() {
	if File_proto_testservice_testservice_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_testservice_testservice_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFoosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_testservice_testservice_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFoosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_testservice_testservice_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_testservice_testservice_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFoobarsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_testservice_testservice_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFoobarsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_testservice_testservice_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Foobar); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_testservice_testservice_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_testservice_testservice_proto_goTypes,
		DependencyIndexes: file_proto_testservice_testservice_proto_depIdxs,
		MessageInfos:      file_proto_testservice_testservice_proto_msgTypes,
	}.Build()
	File_proto_testservice_testservice_proto = out.File
	file_proto_testservice_testservice_proto_rawDesc = nil
	file_proto_testservice_testservice_proto_goTypes = nil
	file_proto_testservice_testservice_proto_depIdxs = nil
}
